apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  # Airflow connections and variables
  AIRFLOW__CORE__FERNET_KEY: xxxx=  # Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow
  AIRFLOW_VAR_HUGGINGFACE_API_KEY: xxxx