apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
  labels:
    app: airflow
    airflow-component: logs
spec:
  accessModes:
    - ReadWriteOnce  # Use ReadWriteMany if available
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data-pvc
  namespace: airflow
  labels:
    app: airflow
    airflow-component: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard