apiVersion: v1
kind: Pod
metadata:
  name: dummy-name  # This is a placeholder and will be replaced by Airflow
  namespace: airflow
  labels:
    app: airflow-worker
spec:
  containers:
    - name: base  # The name 'base' is required by Airflow
      image: localhost:5000/airflow:0.0.1 # This will be replaced by the correct image
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      volumeMounts:
        - name: airflow-data
          mountPath: "/opt/airflow/data"
        - name: airflow-logs
          mountPath: "/opt/airflow/logs"
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1000m" 
          memory: "2Gi"
      env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-metadata
              key: connection
  volumes:
    - name: airflow-data
      persistentVolumeClaim:
        claimName: airflow-data-pvc
    - name: airflow-logs
      persistentVolumeClaim:
        claimName: airflow-logs-pvc
  restartPolicy: Never